AWE/src/objects/Advance_Workflow__c.object
<CustomObject>
    <description>This object holds the definition of the workflows for standard and custom objects</description>
    <fields>
        <fullName>is_Log_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If flag is  on AWE captures run time details on system methods and values involved. To set the flag on Click the Apex log switch button to initiate activation or deactivation</inlineHelpText>
        <label>Apex Log is Enabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Advance Workflow</label>
    <nameField>
        <label>Advance Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advance Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/classes/EnableLogsForAWEExtensions.cls
public with sharing class EnableLogsForAWEExtensions {
	public Advance_Workflow__c advWorkflow{get; set;}
	
	public EnableLogsForAWEExtensions(ApexPages.StandardController stdController){
		Id advWFId = (ID)stdController.getId();
		if(advWFId != null){
			for(Advance_Workflow__c advWF : [select id , is_Log_Enabled__c from Advance_Workflow__c where id = : advWFId]){
				advWorkflow = advWF;
			}
		}
	}
	
	public PageReference updateLogging(){
		if(advWorkflow != null){
			advWorkflow.is_Log_Enabled__c = !advWorkflow.is_Log_Enabled__c;
			try{
				update advWorkflow;
				return new PageReference('/'+advWorkflow.id);
			}catch(Exception ex){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage()));
        		return null;
			}
		}
		return null;
	}

}