AWE/src/objects/Advance_Workflow__c.object
<CustomObject>
    <description>This object holds the definition of the workflows for standard and custom objects</description>
    <fields>
        <fullName>Object__c</fullName>
        <description>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</description>
        <inlineHelpText>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Advance Workflow</label>
    <nameField>
        <label>Advance Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advance Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/objects/Rule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Advance_Workflow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Advance Workflow</label>
        <referenceTo>Advance_Workflow__c</referenceTo>
        <relationshipLabel>Rules</relationshipLabel>
        <relationshipName>Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/objects/Rule_Execution_History__c.object
<CustomObject>
    <fields>
        <fullName>Actions__c</fullName>
        <label>Actions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Advance_Workflow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Advance Workflow</label>
        <referenceTo>Advance_Workflow__c</referenceTo>
        <relationshipLabel>Rule Execution History</relationshipLabel>
        <relationshipName>Rule_Execution_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Criteria__c</fullName>
        <label>Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Evaluation__c</fullName>
        <label>Evaluation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Execution__c</fullName>
        <label>Execution</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_After_Action_Applied__c</fullName>
        <label>Record After Action Applied</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <label>Record ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <label>Record Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleName__c</fullName>
        <description>RuleName__c</description>
        <label>Rule</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Execution_Status__c</fullName>
        <label>Rule Execution Status</label>
        <picklist>
            <picklistValues>
                <fullName>Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rule_Object__c</fullName>
        <label>Rule_Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Version__c</fullName>
        <label>Rule Version</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Stamp__c</fullName>
        <label>Transaction_Stamp</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Rule Execution History</label>
    <nameField>
        <displayFormat>RH-{0000}</displayFormat>
        <label>History ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Execution History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/classes/AW_ExecutionHistoryController1.cls
// 
// (c) 2014 Appirio, Inc.
//
//  AW_ExecutionHistoryController 1                                                    
//
// This class is used to display history record in various modes
//
// 01 Jul 2014     Peter Babalis     Original
public with sharing class AW_ExecutionHistoryController1 {
	  
		String advId;
		String query;
		
		public string historyBy{get;set;} 
		public string objectName{get;set;}
		
		public List<SelectOption> objOptions    {get;set;}
		
		public List<Rule_Execution_History__c> allHistoryRecords {get;set;}
		
		public ApexPages.StandardSetController setCon {get;set;}
		Public Integer noOfRecords{get; set;}
    	Public Integer size{get;set;}
		
		/*
		  variable that stores this value for which the history needs to be filter
		*/
		public string filterValue{get;set;}
		public string recordCaptureName{get;set;}
		public String recKeyPrefix{get;set;}
		public String ruleKeyPrefix{get;set;}
		
		public AW_ExecutionHistoryController1(Apexpages.StandardController ctrl){
			 advId = ctrl.getId();
			 objectName=[Select  Object__c FROM Advance_Workflow__c WHERE Id =:advId].Object__c;
			 recKeyPrefix = Schema.getGlobalDescribe().get(objectName.toLowerCase()).getDescribe().getKeyPrefix();	
			 ruleKeyPrefix= Schema.getGlobalDescribe().get('Rule__c').getDescribe().getKeyPrefix();	
			 size=20;
			 
		}
		
		public AW_ExecutionHistoryController1(){
			historyBy= ApexPages.currentPage().getParameters().get('historyBy');
		 	filterValue= ApexPages.currentPage().getParameters().get('filterValue');
			buildquery();
			
			allHistoryRecords = database.query(query);
		}
		
		private void buildquery(){
				
			/*
			  build the query for the filter
			*/	
			query='Select CreatedDate, Id,Rule__c,Advance_Workflow__c,Criteria__c,Record_After_Action_Applied__c,	Actions__c,Evaluation__c,Execution__c,Record_ID__c,Record_Name__c,RuleName__c,Rule_Execution_Status__c,	Rule_object__c,	Rule_Version__c,Transaction_Stamp__c FROM Rule_Execution_History__c WHERE Id!=\'\'';
			if(historyBy=='historybyobject'  ){
				query+=' AND Rule_object__c=\''+filterValue+'\'';			
			}else if(historyBy=='historybyrecord'  ){
				query+=' AND Record_ID__c LIKE \''+filterValue+'%\'';  			
			}else if(historyBy=='historybyrule'  ){
				query+=' AND Rule__c LIKE \''+filterValue+'%\'';  			
			}else {
				query+=' AND Transaction_Stamp__c=\''+filterValue+'\'';			
			}
			 
		}
		
		public void loadHistory(){
			
			if(filterValue==null){
				ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.WARNING,'Filter not provided..loading entire history'));
				return;
			}
			
			buildquery();
			
			setCon = new ApexPages.StandardSetController(Database.getQueryLocator(query));
	        setCon.setPageSize(size);
	        noOfRecords = setCon.getResultSize();
			//history = database.query(query);
				
		} 
		
		public List<Rule_Execution_History__c> gethistory(){
			List<Rule_Execution_History__c> historyList = new List<Rule_Execution_History__c>();
	        if(setCon!=null){
		        for(Rule_Execution_History__c a : (List<Rule_Execution_History__c>)setCon.getRecords())
		            historyList.add(a);
	        }
	        return historyList;
		} 
		
		public void initfilters(){
             recordCaptureName ='';
             filterValue='';  
             if(historyBy=='historybyobject' && (filterValue==null || filterValue == '')){
			 	filterValue = objectName;
			 }
        }
		
		public PageReference exportToCSV(){
			PageReference p = new PageReference('/apex/AW_ExecutionHistoryCSV_VF?historyBy='+historyBy+'&filterValue='+filterValue);
			p.setRedirect(true);
			return p;	
		}
		
		
}