AWE/src/objects/Advance_Workflow__c.object
<CustomObject>
    <description>This object holds the definition of the workflows for standard and custom objects</description>
    <fields>
        <fullName>Object__c</fullName>
        <description>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</description>
        <inlineHelpText>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Advance Workflow</label>
    <nameField>
        <label>Advance Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advance Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/objects/Rule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Advance_Workflow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Advance Workflow</label>
        <referenceTo>Advance_Workflow__c</referenceTo>
        <relationshipLabel>Rules</relationshipLabel>
        <relationshipName>Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/objects/RuleCriteria__c.object
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Criteria</relationshipLabel>
        <relationshipName>Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AWE/src/classes/AW_RuleCleanupController.cls
public with sharing class AW_RuleCleanupController {
	
	public string selectedCleanupOpt {get;set;}
	public string objectName {get;set;}
	public String ruleStatus {get;set;}
	public Rule__c rule {get;set;}
	public RuleCriteria__c ruleCriteria {get;set;}
	
	public AW_RuleCleanupController(){
		rule = new Rule__c();
		ruleCriteria = new RuleCriteria__c();
	}
	
	public List<SelectOption> getCleanupOptions(){
		List<SelectOption> cleanupOptions = new List<SelectOption>();
		cleanupOptions.add(new SelectOption('Delete All Rules' , 'Delete All Rules'));
		cleanupOptions.add(new SelectOption('Delete Rules of specific object' , 'Delete Rules of specific object'));
		cleanupOptions.add(new SelectOption('Delete Selected Rule' , 'Delete Selected Rule'));
		return cleanupOptions;
	
	}
	
	public List<SelectOption> getObjectsRelatedToAWE(){
		List<SelectOption> objectsRelatedToAWE = new List<SelectOption>();
		for(Advance_Workflow__c aw : [select id , Object__c from Advance_Workflow__c where Object__c != null]){
			objectsRelatedToAWE.add(new SelectOption(aw.Object__c , aw.Object__c));
		}
		return objectsRelatedToAWE;
	}
	
	public PageReference populateObjectPicklist(){
		return null;
	}
	
	public PageReference cleanupRules(){
		List<Rule__c> rulesToDelete;
		if(selectedCleanupOpt == null || selectedCleanupOpt == ''){
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select a option before clean up')); 
            return null;
		}
		if(selectedCleanupOpt == 'Delete All Rules'){
			rulesToDelete = [select id from Rule__c limit 10];
		}else if(selectedCleanupOpt == 'Delete Rules of specific object'){
			if(objectName == null || objectName == ''){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select a object before with this clean up option')); 
            	return null;
			}
			if(rule.status__c == null || rule.Status__c == ''){
				rulesToDelete = [select id from Rule__c limit 10000];
			}else{
				rulesToDelete = [select id from Rule__c where Status__c = : rule.Status__c limit 10000];
			}
		}else if(selectedCleanupOpt == 'Delete Selected Rule'){
			if(ruleCriteria.rule__c == null){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'Please select a rule before with this clean up option')); 
            	return null;
			}
			rulesToDelete = new List<Rule__c>{new Rule__c(id = ruleCriteria.rule__c)};
		}
		if(!rulesToDelete.isEmpty()){
			try{
				delete rulesToDelete;
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,rulesToDelete.size() + ' Rules are deleted successfully')); 
			}catch(Exception ex){
				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,ex.getMessage())); 
            	return null;
			}
		}
		return null;
	}

}