AWE/src/objects/Advance_Workflow__c.object
<CustomObject>
    <description>This object holds the definition of the workflows for standard and custom objects</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Holds the description of the Workflow</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Advance Workflow doesn&apos;t trigger rule execution until you activate it. To activate a workflow rule, click Enable on the workflow rule detail page. Click Deactivate to prevent  Advance Workflow rules associated to an object  from triggering</description>
        <inlineHelpText>Advance Workflow doesn&apos;t trigger rule execution until you activate it. To activate a workflow rule, click Enable on the workflow rule detail page. Click Deactivate to prevent  Advance Workflow rules associated to an object  from triggering</inlineHelpText>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <description>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</description>
        <inlineHelpText>Captures the Object Name ( Standard or Custom ) for which the advance workflow is created</inlineHelpText>
        <label>Object</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Advance Workflow</label>
    <nameField>
        <label>Advance Workflow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advance Workflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/objects/Rule__c.object
<CustomObject>
    <description>Object to hold the basic information (header ) of the rule. It is related to Rule Actions and Criteria</description>
    <fields>
        <fullName>Advance_Workflow__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Advance Workflow</label>
        <referenceTo>Advance_Workflow__c</referenceTo>
        <relationshipLabel>Rules</relationshipLabel>
        <relationshipName>Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Evaluation_Rule__c</fullName>
        <label>Evaluation Rule</label>
        <picklist>
            <picklistValues>
                <fullName>Record is created or edited and did not previously meet the rule criteria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Record is created or edited</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Click Event</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Incomplete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AWE/src/objects/RuleAction__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <label>Field Name</label>
        <picklist>
            <picklistValues>
                <fullName>ccount Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Site</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Annual Revenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Billing Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Created By</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Data.com Key</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employees</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fax</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Last Modified By</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipping Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIC Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SIC Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ticker Symbol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Website</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Related_Object__c</fullName>
        <label>Related Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Actions</relationshipLabel>
        <relationshipName>Rule_Actions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Update Field</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Insert Related Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert Unrelated Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsert Related Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Upsert Unrelated Object</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insert Classification</fullName>
                <color>#FF0000</color>
            </picklistValues>
            <picklistValues>
                <fullName>Send Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attach Documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chatter Notification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Apex Callout-HTTP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Execute an Apex Job</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Load Iframe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Load a VF Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canvas</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Rule Action</label>
    <nameField>
        <displayFormat>Action #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AWE/src/objects/RuleCriteria__c.object
<CustomObject>
    <description>Object to hold the rule criteria for a rule</description>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <defaultValue>&quot;&lt;auto-detect&gt;&quot;</defaultValue>
        <label>Field Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <picklist>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multi-Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matching_Type__c</fullName>
        <label>Matching Type</label>
        <picklist>
            <picklistValues>
                <fullName>Equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Equal To</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Does Not Contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Starts With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ends With</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Greater Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Or Equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Includes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excludes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Between</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regular Expression</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IsChanged</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Matching_Value__c</fullName>
        <label>Matching Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Related_Object__c</fullName>
        <label>Related Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rule__c</fullName>
        <label>Rule</label>
        <referenceTo>Rule__c</referenceTo>
        <relationshipLabel>Rule Criteria</relationshipLabel>
        <relationshipName>Rule_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Rule Criteria</label>
    <nameField>
        <displayFormat>Criteria #{0000}</displayFormat>
        <label>Reference ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rule Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AWE/src/classes/AW_SimulateWorkflowCapture_Test.cls
@isTest
public with sharing class AW_SimulateWorkflowCapture_Test {
	
	private static Id workflowId;
	private static Rule__c rule1;
	private static Rule__c rule2;
	private static Rule__c rule3;
	
	/*
	*	SetupTest Data
	*/
	private static void setUpData(){
		workflowId = Database.insert(new Advance_Workflow__c(Name='Test Workflow',Object__c='Account',Enabled__c=true,Description__c='This is a test workflow')).getId();
		
		// Create rules 
		
        rule1  = new Rule__c(Name = 'Test rule 1',Object__c = 'Account', Status__c='Draft',Evaluation_Rule__c='Record is created or edited',Description__c='Rule 1 Description');
        insert rule1 ;
        List<RuleCriteria__c> ruleCriterias = new List<RuleCriteria__c>();
        ruleCriterias.add(new RuleCriteria__c(rule__c=rule1.id,related_object__c='Account',  Matching_Type__c='Contains', Matching_Value__c='Test',
                                                            field_name__c='Name',field_API_Name__c='Name',Field_Type__c='Text'));
        
        ruleCriterias.add(new RuleCriteria__c(rule__c=rule1.id,related_object__c='Account',  Matching_Type__c='Not Null', Matching_Value__c='Test',
                                                            field_name__c='OwnerId',field_API_Name__c='OwnerId',Field_Type__c='Text'));
        insert ruleCriterias ;
        RuleAction__c ruleaction1 = new RuleAction__c(rule__c=rule1.id,related_object__c='Account',
                                                            field_name__c='Name',Type__c='Update Field',Value__c='TestUpdate1');
        insert ruleaction1;
        
        rule2  = new Rule__c(Name = 'Test rule 2',Object__c = 'Account', Status__c='Draft',Evaluation_Rule__c='Record is created or edited',Description__c='Rule 2 Description');
        insert rule2 ;
        RuleCriteria__c ruleCriteria2 = new RuleCriteria__c(rule__c=rule2.id,related_object__c='Account',  Matching_Type__c='Contains', Matching_Value__c='Test',
                                                            field_name__c='Name',field_API_Name__c='Name',Field_Type__c='Text');
        insert ruleCriteria2 ;
        RuleAction__c ruleaction2 = new RuleAction__c(rule__c=rule2.id,related_object__c='Account',
                                                            field_name__c='Description',Type__c='Update Field',Value__c='TestUpdate2');
        insert ruleaction2;
        
        rule3  = new Rule__c(Name = 'Test rule 3',Object__c = 'Account', Status__c='Draft',Evaluation_Rule__c='Record is created or edited',Description__c='Rule 3 Description');
        insert rule3 ;
        RuleCriteria__c ruleCriteria3 = new RuleCriteria__c(rule__c=rule3.id,related_object__c='Account',  Matching_Type__c='Contains', Matching_Value__c='Test',
                                                            field_name__c='Name',field_API_Name__c='Name',Field_Type__c='Text');
        insert ruleCriteria3 ;
        RuleAction__c ruleaction3 = new RuleAction__c(rule__c=rule3.id,related_object__c='Account',
                                                            field_name__c='Description',Type__c='Description',Value__c='TestUpdate3');
        insert ruleaction3;
        
        
		
		rule1.Order__c=10;
        rule1.Status__c = 'Active';
        rule1.Execution_Behavior__c='Execute and Exit';
        rule1.Advance_Workflow__c=workflowId;
        rule1.Filter_Logic__c = '1 AND 2';
        update rule1;
        
		rule2.Order__c=20;
        rule2.Status__c = 'Active';
        rule2.Execution_Behavior__c='Execute and Exit';
        rule2.Advance_Workflow__c=workflowId;
        update rule2;
        
        rule3.Order__c=30;
        rule3.Status__c = 'Active';
        rule3.Execution_Behavior__c='Execute and Exit';
        rule3.Advance_Workflow__c=workflowId;
        update rule3;
	}
	
	/*
	*	SetupTest Account Data for test
	*/
	
	private static void setUpAccountData(){
		List<Account> accountsList = new List<Account>{	new Account(Name='Test Account 1'),
														new Account(Name='Test Account 2'),
														new Account(Name='Test Account 3'),
														new Account(Name='Test Account 4')
													  };
		insert accountsList;
	}
	
	/*
	*	test Constructor
	*/
	@isTest
	static void test_Constructor(){
		Test.startTest();
		setUpData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		System.assertNotEquals(true,cls.showInputBlock);
		System.assertEquals('workflow',cls.selectedMode);
		System.assertNotEquals(1,cls.fieldsList.size());
		Test.stopTest();
	}
	
	/*
	*	test getRecordsForUpdate method
	*/
	@isTest
	static void test_getRecordsForUpdate(){
		Test.startTest();
		setUpData();
		setUpAccountData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture  cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		//cls.addObjectField();
		//cls.removeObjectField();
		System.assertNotEquals(true,cls.showInputBlock);
		System.assertEquals('workflow',cls.selectedMode); 
		//System.assertEquals(4,cls.getRecordsForUpdate().size());
		Test.stopTest();
	}
	
	/*
	*	test simulateWorkflow method	
	*/
	@isTest
	static void test_simulateWorkflow(){
		Test.startTest();
		setUpData();
		setUpAccountData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture  cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		
		cls.selectedMode = 'rule';
		cls.operationType = 'update';
		cls.selectedRule = rule1.id;
		cls.recordName = 'Test Account 1,Test Account 2,Test Account 3';
		cls.ruleCriterias();
		PageReference pReference = cls.simulateWorkflow();
		Test.stopTest();
	
	}
	
	/*
	*	test InputRecord method
	*/
	@isTest
	static void test_InputRecord(){
		Test.startTest();
		setUpData();
		setUpAccountData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture  cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		Account account = [Select Name from Account where Name = 'Test Account 1' limit 1];
		Map<Id,SObject> recdBefore = new Map<Id,SObject>{account.id => account};
		Advance_Workflow__c workFlow1 = [select Name, Object__c from Advance_Workflow__c where id =:workflowId];
		List<AW_SimulateWorkflowCapture.ObjectFields> objectFieldsList = new List<AW_SimulateWorkflowCapture.ObjectFields>();
		//objectFieldsList.add(new AW_SimulateWorkflowCapture.ObjectFields(1,cls.fieldsList));
		SObject returnedSObject = AW_SimulateWorkflowCapture.InputRecord(recdBefore, workFlow1, objectFieldsList);
		//System.debug('********OutPutSObject****'+returnedSObject);
		Test.stopTest();
	}
	
	/*
	*	test getRules method
	*/
	@isTest
	static void test_getRules(){
		Test.startTest();
		setUpData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture  cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		System.assertEquals(3,cls.getRules().size());
		Test.stopTest();
	}
	
	/*
	*	test checkSelectedMode method
	*/
	@isTest
	static void test_checkSelectedMode(){
		Test.startTest();
		setUpData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		cls.checkSelectedMode();
		
		// Test with value
		cls.selectedMode = 'workflow';
		cls.operationType = 'create';
		cls.checkSelectedMode();
		System.assertEquals(3,cls.criteriaList.size());
		Test.stopTest();
	}
	
	/*
	*	test ruleCriterias method
	*/
	@isTest
	static void test_ruleCriterias(){
		Test.startTest();
		setUpData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		
		// Test with value
		cls.selectedMode = 'rule';
		cls.operationType = 'update';
		cls.ruleCriterias();
		
		// Test selected mode is null
		List<Apexpages.Message> messages = ApexPages.getMessages();
		System.assertEquals(1, messages.size());
		System.assertNotEquals(true, cls.showInputBlock);
		Test.stopTest();
	}
	
	/*
	*	test simulateWorkflow method	
	*/
	@isTest
	static void test_addMore(){
		Test.startTest();
		setUpData();
		setUpAccountData();
		Advance_Workflow__c workflow = [SELECT Id, Name FROM Advance_Workflow__c WHERE Id=:workflowId LIMIT 1];
		System.Test.setCurrentPageReference(new PageReference('/apex/x?id='+workflowId));
		AW_SimulateWorkflowCapture  cls = new AW_SimulateWorkflowCapture(new ApexPages.standardController(workflow));
		
		cls.selectedMode = 'rule';
		cls.operationType = 'update';
		cls.selectedRule = rule1.id;
		cls.recordName = 'Test Account 1,Test Account 2,Test Account 3';
		cls.ruleCriterias();
		cls.addmorefilter();
		cls.addmorefilter();
		cls.addmorefilter();
		cls.toremovecounter =  String.valueOf(cls.FilterWrapper.size() - 1);
		System.assert(cls.FilterWrapper.size() > 0);
		cls.deleteFilter();
		Test.stopTest();
	
	}
}