AWE/src/objects/Apex_Log__c.object
<CustomObject>
    <description>This object provides a way to log audit, error and exception information from apex code which is persistent (v. debug logs which are not) and which can be further actioned with workflows.</description>
    <fields>
        <fullName>Exception_Stack_Trace_String__c</fullName>
        <description>Exception Stack Trace String from the SF Exception Object that was caught.</description>
        <inlineHelpText>Exception Stack Trace String from the SF Exception Object that was caught.</inlineHelpText>
        <label>Exception Stack Trace String</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Exception Type Name from the SF Exception Object that was caught.</description>
        <inlineHelpText>Exception Type Name from the SF Exception Object that was caught.</inlineHelpText>
        <label>Exception Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <picklist>
            <picklistValues>
                <fullName>ERROR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WARN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEBUG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>This is the primary field to contain the error, audit or exception messages we wish to log.</description>
        <inlineHelpText>This is the primary field to contain the error, audit or exception messages we wish to log.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Message__c</fullName>
        <description>Optional status message for adding an additional level of detail or segmentation to a log record.</description>
        <inlineHelpText>Optional status message for adding an additional level of detail or segmentation to a log record.</inlineHelpText>
        <label>Status Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>class_name__c</fullName>
        <description>Class (or Trigger) name of relevant apex code the log record is generated from.</description>
        <externalId>true</externalId>
        <inlineHelpText>Class (or Trigger) name of relevant apex code the log record is generated from.</inlineHelpText>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>method_name__c</fullName>
        <description>The name of the Apex method creating the audit object.</description>
        <externalId>true</externalId>
        <inlineHelpText>The name of the Apex method creating the audit object.</inlineHelpText>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>start_dtm__c</fullName>
        <description>DateTime stamp at which the logging process began.</description>
        <inlineHelpText>DateTime stamp at which the logging process began.</inlineHelpText>
        <label>Start DTM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>stop_dtm__c</fullName>
        <description>DateTime stamp at which logging process was ended.</description>
        <inlineHelpText>DateTime stamp at which logging process was ended.</inlineHelpText>
        <label>Stop DTM</label>
        <type>DateTime</type>
    </fields>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Log</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AWE/src/classes/AW_ApexLogsController.cls
public with sharing class AW_ApexLogsController {

	public Apex_Log__c apexLogger{get;set;}
	public Boolean isResult {get;set;}
	
	public List<Apex_Log__c> apexLoggerResults{get{
		if(stdController != null){
            	return (List<Apex_Log__c>)stdController.getRecords();            	
        }else
                return new List<Apex_Log__c>();
	}set;}
	@TestVisible
  	private static Integer PAGE_SIZE = 10;
	private ApexPages.StandardSetController stdController;
	
	public AW_ApexLogsController(){
		apexLogger = new Apex_Log__c();
		isResult = false;
	}
	
	public PageReference search(){
		String soqlQuery = 'Select Name, class_name__c, Owner.Name, Exception_Stack_Trace_String__c , start_dtm__c, Exception_Type__c, Log_Type__c , Message__c, method_name__c , Status_Message__c'
     			   			 + ' FROM Apex_Log__c ';
        String filterLogic = '';
        Id ownerId = apexlogger.OwnerId;
        DateTime stDate = apexlogger.start_dtm__c;
        DateTime endDate = apexlogger.stop_dtm__c;
        if(ownerId != null){
        	filterLogic = ' ownerId = : ownerId ';
        }
        if(stDate !=  null){
        	if(filterLogic == ''){
        		filterLogic += ' start_dtm__c > =  : stDate ';
        	}else{
        		filterLogic += ' AND start_dtm__c > =  : stDate ';
        	}
        }
        if(endDate !=  null){
        	if(filterLogic == ''){
        		filterLogic += ' start_dtm__c < =  : endDate';
        	}else{
        		filterLogic += ' AND start_dtm__c < =  : endDate';
        	}
        }
        soqlQuery += (filterLogic != '' ?  ' WHERE ' + filterLogic : '') + ' Order by start_dtm__c DESC limit 10000';
       System.debug('::soqlQuery'+soqlQuery);
      stdController = new ApexPages.StandardSetController(Database.query(soqlQuery));
      // sets the number of records in each page set
      stdController.setPageSize(PAGE_SIZE);
      isResult = true;
      return null;
	}
	
	//Boolean to check if there are more records after the present displaying records
    public Boolean hasNext{
        get
        {
            if(stdController != null){
                return stdController.getHasNext();
            }
            return false;
        }set;}
 
    //Boolean to check if there are more records before the present displaying records
    public Boolean hasPrevious{
        get
        {
            if(stdController != null){
                return stdController.getHasPrevious();
            }
            return false;
        }set;}
 
    //Page number of the current displaying records
    public Integer pageNumber{
        get
        {
            if(stdController != null){
                return stdController.getPageNumber();
            }
            return 0;
        }set;}

     //Page number of the Size
    public Integer pageSize{
        get
        {
            if(stdController != null){
                return stdController.getPageSize();
            }
            return 0;
        }set;}
    
    //Returns the previous page of records
    public void previous(){
        if(stdController != null){
            stdController.previous();
        }
    }
 
    //Returns the next page of records
    public void next(){
       if(stdController != null){
            stdController.next();
        }
    }
    
	
}