AWE/src/objects/Apex_Log__c.object
<CustomObject>
    <description>This object provides a way to log audit, error and exception information from apex code which is persistent (v. debug logs which are not) and which can be further actioned with workflows.</description>
    <fields>
        <fullName>Exception_Type__c</fullName>
        <description>Exception Type Name from the SF Exception Object that was caught.</description>
        <inlineHelpText>Exception Type Name from the SF Exception Object that was caught.</inlineHelpText>
        <label>Exception Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Log_Type__c</fullName>
        <label>Log Type</label>
        <picklist>
            <picklistValues>
                <fullName>ERROR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WARN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INFO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DEBUG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <description>This is the primary field to contain the error, audit or exception messages we wish to log.</description>
        <inlineHelpText>This is the primary field to contain the error, audit or exception messages we wish to log.</inlineHelpText>
        <label>Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>class_name__c</fullName>
        <description>Class (or Trigger) name of relevant apex code the log record is generated from.</description>
        <externalId>true</externalId>
        <inlineHelpText>Class (or Trigger) name of relevant apex code the log record is generated from.</inlineHelpText>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>method_name__c</fullName>
        <description>The name of the Apex method creating the audit object.</description>
        <externalId>true</externalId>
        <inlineHelpText>The name of the Apex method creating the audit object.</inlineHelpText>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>start_dtm__c</fullName>
        <description>DateTime stamp at which the logging process began.</description>
        <inlineHelpText>DateTime stamp at which the logging process began.</inlineHelpText>
        <label>Start DTM</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>stop_dtm__c</fullName>
        <description>DateTime stamp at which logging process was ended.</description>
        <inlineHelpText>DateTime stamp at which logging process was ended.</inlineHelpText>
        <label>Stop DTM</label>
        <type>DateTime</type>
    </fields>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>LOG-{000000000}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Apex Log</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

AWE/src/classes/AW_ApexLogsController_Test.cls
/**
 * Test Class for AW_ApexLogsController
 */
@isTest
private class AW_ApexLogsController_Test {
	@isTest
    static void testSearch() {
       Apex_Log__c apexLog = new Apex_Log__c(start_dtm__c = DateTime.now().addMinutes(-10) , 
        						class_name__c = 'AW_RuleActionsController', Exception_Type__c = 'Error', Log_Type__c = 'DEBUG' , Message__c = 'Debug : This is my apex Log', method_name__c = 'All');
       insert apexLog;
       AW_ApexLogsController apexLogController = new AW_ApexLogsController();
       apexLogController.apexLogger.ownerId = userInfo.getUserID();
       apexLogController.apexLogger.start_dtm__c = DateTime.now().addMinutes(-15);
       apexLogController.search();
       System.assert(apexLogController.apexLoggerResults.size() > 0 , 'Actual Apex Log Size :' +apexLogController.apexLoggerResults.size());
    }
    
    @isTest
    static void testPagination() {
       List<Apex_Log__c> apexLogs = new List<Apex_Log__c>();
       for(Integer i = 0; i < 30; i++){
       		apexLogs.add(new Apex_Log__c(start_dtm__c = DateTime.now().addMinutes(-10 + i) , 
        						class_name__c = 'AW_RuleActionsController', Exception_Type__c = 'Error', Log_Type__c = 'DEBUG' , Message__c = 'Debug : This is my apex Log' + i , method_name__c = 'All'));
       }
       insert apexLogs;
       AW_ApexLogsController apexLogController = new AW_ApexLogsController();
     
       apexLogController.apexLogger.start_dtm__c = DateTime.now().addMinutes(-30);
       apexLogController.apexLogger.stop_dtm__c = DateTime.now().addMinutes(60);
       apexLogController.search();
       System.assert(apexLogController.apexLoggerResults.size() > 0 , 'Actual Apex Log Size :' +apexLogController.apexLoggerResults.size());
       System.assert(apexLogController.hasNext);
       apexLogController.next();
       System.assert(apexLogController.pageNumber > 0);
       System.assert(apexLogController.pageSize > 0);
       System.assert(apexLogController.hasPrevious);
       apexLogController.previous();
    }
}